### ISSUE TITLE
Does not convert keys and metal using conversion rate

### ISSUE THREAD

**Issue by Nicklason** [Nicklason/tf2-automatic#223]
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like**

The bot says that the price is 13 keys 55 ref, but when attempting to buy the item it says that it will offer you the item for 14 keys. When checking what the bot valued keys at it said that the price was 55 ref. So instead of saying 13 keys 55 ref, then the bot should just say 14 keys.

Listings should also use this price, but that would mean that the bot needs to update listings when the price of keys change.

**Describe alternatives you've considered**

The alternative is that we don't change anything and let the bot work like it does now. It seems like a lot of work just to make the bot say the "most accurate" price.

**Additional context**

**Comment by danocmx** [comment]
Another outtake I received: 
```
Trade #xxxxxxxxx with 765611xxxxxxx is accepted. Summary:
Asked: 941.88 ref (Strange Killstreak Australium Knife)
Offered: 17 keys, 5 ref (Mann Co. Supply Crate Key x17, Refined Metal x5)
```

Bot didn't convert knife value even though the payment was in keys.

**Comment by idinium96** [comment]
This is my own solution and I would to suggest it.

Add the conversion rate to the bot's successful trade feedback when it involve key(s):
![IMG_20200227_063554](https://user-images.githubusercontent.com/47635037/75395023-71bf0a80-592c-11ea-81b8-dce5b426645f.jpg)
![IMG_20200227_063554](https://user-images.githubusercontent.com/47635037/75395038-7b487280-592c-11ea-83ee-0cb7261a59f7.jpg)

So that the bot's owner can manually calculate if it's correct or he got extras. The bot usually does it job very well.
