### ISSUE TITLE
Missing required environmet variable "STEAM_ACCOUNT_NAME"

### ISSUE THREAD

**Issue by kl1menkov** [Nicklason/tf2-automatic#364]
This error appears when the bot starts. I followed the installation and configuration instructions , but the bot doesn't see the file .env for some reason.

![Screenshot_1](https://user-images.githubusercontent.com/61388322/75961915-ed442d00-5ed3-11ea-9dd4-b8e1af26eda6.png)
![Screenshot_2](https://user-images.githubusercontent.com/61388322/75961928-f1704a80-5ed3-11ea-9906-29968e7172d1.png)

**Comment by Nicklason** [comment]
You have not followed the wiki. Please follow it closely and if you still need help then ask in the discord server.

Just to speed up the process for you, the bot just says that you are missing a required config property. The problem is that you didn’t make a file called “.env”, you called it “tf2-automatic.env”, this is why following the wiki is important, instead of just going to the conclusion that something is wrong with the bot.

**Comment by Nicklason** [comment]
You could also have looked at previously made issues: https://github.com/Nicklason/tf2-automatic/issues/169
