### ISSUE TITLE
Non-Craftable items in Craftable listings after update.

### ISSUE THREAD

**Issue by Anton-Beresansky** [Nicklason/tf2-automatic#57]
After update bot creates listings for Non-Craftable items as Craftable items on backpack.tf.
Tell me what you need to detect the issue reason (logs, etc...)

**Comment by Nicklason** [comment]
It is because of the changes I made yesterday, the bot uses a newer version of the tf2-items dependency. The newer version could accept cached schemas, but the way it got the name of items was not working properly. It has been fixed https://github.com/Nicklason/node-tf2-items/commit/47e80a4047c3b4d0544f2d5f62c102fcdfb0f882
